### ISSUE TITLE
JSON Is Not Valid when "style" item is missing

### ISSUE THREAD

**Issue by isaaacporter** [jeffderek/zoom-native-room-controls-preview#11]
When the "style" JSON item is missing, the tool reports as "JSON Is Not Valid", but this is a valid configuration that Zoom will accept. 

[jsonWithNoStyle.txt](https://github.com/jeffderek/zoom-native-room-controls-preview/files/10437109/jsonWithNoStyle.txt)

**Comment by jeffderek** [comment]
Fixed
