### ISSUE TITLE
JSON is not valid when "Rule" exists, but is empty with more than a just the 2 brackets "[]"

### ISSUE THREAD

**Issue by isaaacporter** [jeffderek/zoom-native-room-controls-preview#13]
Zoom Presents an "Status Code 451" error for the following JSON examples:
![image](https://github.com/jeffderek/zoom-native-room-controls-preview/assets/66755851/24152791-b622-4af7-bc5a-6d365eec4ca4)
![image](https://github.com/jeffderek/zoom-native-room-controls-preview/assets/66755851/58a4af94-e4da-44e8-9ed9-6dcc5b0365e2)

Because there is a space, or any other amount of space/tabs/LFs, between "[" and "]", it throws an error. The following code is valid. 
![image](https://github.com/jeffderek/zoom-native-room-controls-preview/assets/66755851/082a4406-9316-4a59-9b17-3b96791ff80c)

This isn't necessarily a huge deal, but I experienced it today and saw some chatter on the internet about it with no concrete answers. I have access to a Zoom Room Admin account, so I tested around to figure out what causes it. 
https://devforum.zoom.us/t/request-failed-status-code-451-when-deploy-zoom-room-native-control/68549

**Comment by isaaacporter** [comment]
Here's the image of Zoom's error for the top two examples:
![image](https://github.com/jeffderek/zoom-native-room-controls-preview/assets/66755851/4f1da5b9-89ab-4bb8-aced-78c655e464c2)

**Comment by jeffderek** [comment]
That should take care of it.  I was relying on json.Parse to tell me if the json itself was valid, Zoom must be using some strange json parser on their side that doesn't count that as valid.
